name: react
version: 0.8.0
author: Clean Team <clean@vacuumlabs.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: http://cleandart.github.io/react-dart/
dependencies:
  browser: '>=0.9.0 <0.11.0'
  quiver: '>=0.18.2 < 0.19.0'
  js: '^0.6.0-beta'
dev_dependencies:
  unittest: '>=0.11.0'
